WIP Add basic Github App authentication support

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -16,21 +16,49 @@ payload="$(cat <&0)"
 load_pubkey "$payload"
 configure_https_tunnel "$payload"
 configure_git_ssl_verification "$payload"
-configure_credentials "$payload"
 
-uri=$(jq -r '.source.uri // ""' <<< "$payload")
-branch=$(jq -r '.source.branch // ""' <<< "$payload")
-paths="$(jq -r '(.source.paths // ["."])[]' <<< "$payload")" # those "'s are important
-ignore_paths="$(jq -r '":!" + (.source.ignore_paths // [])[]' <<< "$payload")" # these ones too
-tag_filter=$(jq -r '.source.tag_filter // ""' <<< "$payload")
-tag_regex=$(jq -r '.source.tag_regex // ""' <<< "$payload")
-git_config_payload=$(jq -r '.source.git_config // []' <<< "$payload")
-ref=$(jq -r '.version.ref // ""' <<< "$payload")
-skip_ci_disabled=$(jq -r '.source.disable_ci_skip // false' <<< "$payload")
-filter_include=$(jq '.source.commit_filter.include // []' <<< "$payload")
-filter_exclude=$(jq '.source.commit_filter.exclude // []' <<< "$payload")
-version_depth=$(jq -r '.source.version_depth // 1' <<< "$payload")
+uri=$(jq -r '.source.uri // ""' <<<"$payload")
+branch=$(jq -r '.source.branch // ""' <<<"$payload")
+paths="$(jq -r '(.source.paths // ["."])[]' <<<"$payload")"                   # those "'s are important
+ignore_paths="$(jq -r '":!" + (.source.ignore_paths // [])[]' <<<"$payload")" # these ones too
+tag_filter=$(jq -r '.source.tag_filter // ""' <<<"$payload")
+tag_regex=$(jq -r '.source.tag_regex // ""' <<<"$payload")
+git_config_payload=$(jq -r '.source.git_config // []' <<<"$payload")
+ref=$(jq -r '.version.ref // ""' <<<"$payload")
+skip_ci_disabled=$(jq -r '.source.disable_ci_skip // false' <<<"$payload")
+filter_include=$(jq '.source.commit_filter.include // []' <<<"$payload")
+filter_exclude=$(jq '.source.commit_filter.exclude // []' <<<"$payload")
+version_depth=$(jq -r '.source.version_depth // 1' <<<"$payload")
+github_app_account=$(jq -r '.source.github_app_account // ""' <<<"$payload")
+github_app_id=$(jq -r '.source.github_app_id // ""' <<<"$payload")
+github_app_private_key=$(jq -r '.source.github_app_private_key // ""' <<<"$payload")
+github_app_token_duration_mins=$(jq -r '.source.github_app_token_duration // "3"' <<<"$payload")
 reverse=false
+
+# Github App configuration
+if [ -n "${github_app_account}" ] && [ -n "${github_app_id}" ] && [ -n "${github_app_private_key}" ]; then
+  echo "${github_app_private_key}" >gha_privatekey.pem
+  gha_jwt_token=$(jwt encode --alg RS256 --secret @gha_privatekey.pem --iss "${github_app_id}" --exp "+${github_app_token_duration_mins}min")
+  rm -f gha_privatekey.pem
+  gha_installation_id=$(curl -s -X GET -H "Authorization: Bearer ${gha_jwt_token}" -H "Accept: application/vnd.github+json" https://api.github.com/app/installations |
+    jq -r --arg target "${github_app_account}" 'map(select(.account.login==$target)) | .[0].id // ""')
+  if [ -z "${gha_installation_id}" ]; then
+    echo "failed to get your Github App installation id. Check your Github App configuration of this resource or on GitHub." >&2
+    exit 1
+  fi
+  github_app_token=$(curl -s -X POST -H "Authorization: Bearer ${gha_jwt_token}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/app/installations/${gha_installation_id}/access_tokens" | jq -r '.token')
+  if [ -z "${github_app_token}" ]; then
+    echo "failed to get Github App token" >&2
+    exit 1
+  fi
+  if ! [[ $uri =~ ^https://github\.com ]]; then
+    echo "Github repository address must begin https:// when using Github App authentication" >&2
+    exit 1
+  fi
+  configure_credentials "$(jq -nr --arg token "${github_app_token}" '{ "source": { "username": "x-username-access", "password": $token } }')"
+else
+  configure_credentials "$payload"
+fi
 
 configure_git_global "${git_config_payload}"
 
@@ -38,15 +66,14 @@ destination=$TMPDIR/git-resource-repo-cache
 
 # Optimization when last commit only is checked and skip ci is disabled
 # Get the commit id with git ls-remote instead of downloading the whole repo
-if [ "$skip_ci_disabled" = "true" ] && \
-   [ "$version_depth" = "1" ] && \
-   [ "$paths" = "." ] && \
-   [ -z "$ignore_paths" ] && \
-   [ -z "$tag_filter" ] && \
-   [ -z "$tag_regex" ] && \
-   jq -e 'length == 0' <<<"$filter_include" && \
-   jq -e 'length == 0' <<<"$filter_exclude"
-then
+if [ "$skip_ci_disabled" = "true" ] &&
+  [ "$version_depth" = "1" ] &&
+  [ "$paths" = "." ] &&
+  [ -z "$ignore_paths" ] &&
+  [ -z "$tag_filter" ] &&
+  [ -z "$tag_regex" ] &&
+  jq -e 'length == 0' <<<"$filter_include" &&
+  jq -e 'length == 0' <<<"$filter_exclude"; then
   branchflag="HEAD"
   if [ -n "$branch" ]; then
     branchflag="$branch"
@@ -63,16 +90,14 @@ then
 fi
 
 tagflag=""
-if [ -n "$tag_filter" ] || [ -n "$tag_regex" ] ; then
+if [ -n "$tag_filter" ] || [ -n "$tag_regex" ]; then
   tagflag="--tags"
 else
   tagflag="--no-tags"
 fi
 
-for filter in "$filter_include" "$filter_exclude"
-do
-  if jq -e 'type != "array"' <<<"$filter"
-  then
+for filter in "$filter_include" "$filter_exclude"; do
+  if jq -e 'type != "array"' <<<"$filter"; then
     echo 'invalid commit filter (expected array of strings)'
     echo "$filter"
     exit 1
@@ -117,37 +142,32 @@ fi
 if [ "$paths" = "." ] && [ -z "$ignore_paths" ]; then
   paths_search=""
 else
-  paths_search=`echo "-- $paths $ignore_paths" | tr "\n\r" " "`
+  paths_search=$(echo "-- $paths $ignore_paths" | tr "\n\r" " ")
 fi
 
 list_command="git rev-list --all --first-parent $log_range $paths_search"
-if jq -e 'length > 0' <<<"$filter_include"
-then
-    list_command+=" | git rev-list --stdin --date-order  --first-parent --no-walk=unsorted "
-    whitelist_items=$(echo $filter_include | jq -r -c '.[]')
-    for wli in "$whitelist_items"
-    do
-        list_command+=" --grep=\"$wli\""
-    done
+if jq -e 'length > 0' <<<"$filter_include"; then
+  list_command+=" | git rev-list --stdin --date-order  --first-parent --no-walk=unsorted "
+  whitelist_items=$(echo $filter_include | jq -r -c '.[]')
+  for wli in "$whitelist_items"; do
+    list_command+=" --grep=\"$wli\""
+  done
 fi
 
-if jq -e 'length > 0' <<<"$filter_exclude"
-then
-    list_command+=" | git rev-list --stdin --date-order  --invert-grep --first-parent --no-walk=unsorted "
-    blacklist_items=$(echo $filter_exclude | jq -r -c '.[]')
-    for bli in "$blacklist_items"
-    do
-        list_command+=" --grep=\"$bli\""
-    done
+if jq -e 'length > 0' <<<"$filter_exclude"; then
+  list_command+=" | git rev-list --stdin --date-order  --invert-grep --first-parent --no-walk=unsorted "
+  blacklist_items=$(echo $filter_exclude | jq -r -c '.[]')
+  for bli in "$blacklist_items"; do
+    list_command+=" --grep=\"$bli\""
+  done
 fi
-
 
 if [ "$skip_ci_disabled" != "true" ]; then
   list_command+=" | git rev-list --stdin --date-order  --grep=\"\\[ci\\sskip\\]\" --grep=\"\\[skip\\sci\\]\" --invert-grep --first-parent --no-walk=unsorted"
 fi
 
 replace_escape_chars() {
-  sed -e 's/[]\/$*.^[]/\\&/g' <<< $1
+  sed -e 's/[]\/$*.^[]/\\&/g' <<<$1
 }
 
 lines_including_and_after() {
@@ -155,7 +175,7 @@ lines_including_and_after() {
   sed -ne "/$escaped_string/,$ p"
 }
 
-get_commit(){
+get_commit() {
   for tag in $*; do
     commit=$(git rev-list -n 1 $tag)
     jq -n '{ref: $tag, commit: $commit}' --arg tag $tag --arg commit $commit
@@ -163,14 +183,12 @@ get_commit(){
 }
 
 #if no range is selected just grab the last commit that fits the filter
-if [ -z "$log_range" ]
-then
-    list_command+="| git rev-list --stdin --date-order --no-walk=unsorted -$version_depth --reverse"
+if [ -z "$log_range" ]; then
+  list_command+="| git rev-list --stdin --date-order --no-walk=unsorted -$version_depth --reverse"
 fi
 
-if [ "$reverse" == "true" ]
-then
-    list_command+="| git rev-list --stdin --date-order  --first-parent --no-walk=unsorted --reverse"
+if [ "$reverse" == "true" ]; then
+  list_command+="| git rev-list --stdin --date-order  --first-parent --no-walk=unsorted --reverse"
 fi
 
 if [ -n "$tag_filter" ]; then
diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -29,34 +29,62 @@ load_pubkey "$payload"
 load_git_crypt_key "$payload"
 configure_https_tunnel "$payload"
 configure_git_ssl_verification "$payload"
-configure_credentials "$payload"
 
-uri=$(jq -r '.source.uri // ""' <<< "$payload")
-branch=$(jq -r '.source.branch // ""' <<< "$payload")
-git_config_payload=$(jq -r '.source.git_config // []' <<< "$payload")
-ref=$(jq -r '.version.ref // "HEAD"' <<< "$payload")
-override_branch=$(jq -r '.version.branch // ""' <<< "$payload")
-depth=$(jq -r '(.params.depth // 0)' <<< "$payload")
-fetch=$(jq -r '(.params.fetch // [])[]' <<< "$payload")
-submodules=$(jq -r '(.params.submodules // "all")' <<< "$payload")
-submodule_recursive=$(jq -r '(.params.submodule_recursive // true)' <<< "$payload")
-submodule_remote=$(jq -r '(.params.submodule_remote // false)' <<< "$payload")
-commit_verification_key_ids=$(jq -r '(.source.commit_verification_key_ids // [])[]' <<< "$payload")
-commit_verification_keys=$(jq -r '(.source.commit_verification_keys // [])[]' <<< "$payload")
-tag_filter=$(jq -r '.source.tag_filter // ""' <<< "$payload")
-tag_regex=$(jq -r '.source.tag_regex // ""' <<< "$payload")
-fetch_tags=$(jq -r '.params.fetch_tags' <<< "$payload")
-gpg_keyserver=$(jq -r '.source.gpg_keyserver // "hkp://keyserver.ubuntu.com/"' <<< "$payload")
-disable_git_lfs=$(jq -r '(.params.disable_git_lfs // false)' <<< "$payload")
-clean_tags=$(jq -r '(.params.clean_tags // false)' <<< "$payload")
-short_ref_format=$(jq -r '(.params.short_ref_format // "%s")' <<< "$payload")
-timestamp_format=$(jq -r '(.params.timestamp_format // "iso8601")' <<< "$payload")
-describe_ref_options=$(jq -r '(.params.describe_ref_options // "--always --dirty --broken")' <<< "$payload")
-search_remote_refs_flag=$(jq -r '(.source.search_remote_refs // false)' <<< "$payload")
+uri=$(jq -r '.source.uri // ""' <<<"$payload")
+branch=$(jq -r '.source.branch // ""' <<<"$payload")
+git_config_payload=$(jq -r '.source.git_config // []' <<<"$payload")
+ref=$(jq -r '.version.ref // "HEAD"' <<<"$payload")
+override_branch=$(jq -r '.version.branch // ""' <<<"$payload")
+depth=$(jq -r '(.params.depth // 0)' <<<"$payload")
+fetch=$(jq -r '(.params.fetch // [])[]' <<<"$payload")
+submodules=$(jq -r '(.params.submodules // "all")' <<<"$payload")
+submodule_recursive=$(jq -r '(.params.submodule_recursive // true)' <<<"$payload")
+submodule_remote=$(jq -r '(.params.submodule_remote // false)' <<<"$payload")
+commit_verification_key_ids=$(jq -r '(.source.commit_verification_key_ids // [])[]' <<<"$payload")
+commit_verification_keys=$(jq -r '(.source.commit_verification_keys // [])[]' <<<"$payload")
+tag_filter=$(jq -r '.source.tag_filter // ""' <<<"$payload")
+tag_regex=$(jq -r '.source.tag_regex // ""' <<<"$payload")
+fetch_tags=$(jq -r '.params.fetch_tags' <<<"$payload")
+gpg_keyserver=$(jq -r '.source.gpg_keyserver // "hkp://keyserver.ubuntu.com/"' <<<"$payload")
+disable_git_lfs=$(jq -r '(.params.disable_git_lfs // false)' <<<"$payload")
+clean_tags=$(jq -r '(.params.clean_tags // false)' <<<"$payload")
+short_ref_format=$(jq -r '(.params.short_ref_format // "%s")' <<<"$payload")
+timestamp_format=$(jq -r '(.params.timestamp_format // "iso8601")' <<<"$payload")
+describe_ref_options=$(jq -r '(.params.describe_ref_options // "--always --dirty --broken")' <<<"$payload")
+search_remote_refs_flag=$(jq -r '(.source.search_remote_refs // false)' <<<"$payload")
+github_app_account=$(jq -r '.source.github_app_account // ""' <<<"$payload")
+github_app_id=$(jq -r '.source.github_app_id // ""' <<<"$payload")
+github_app_private_key=$(jq -r '.source.github_app_private_key // ""' <<<"$payload")
+github_app_token_duration_mins=$(jq -r '.source.github_app_token_duration // "3"' <<<"$payload")
+
+# Github App configuration
+if [ -n "${github_app_account}" ] && [ -n "${github_app_id}" ] && [ -n "${github_app_private_key}" ]; then
+  echo "${github_app_private_key}" >gha_privatekey.pem
+  gha_jwt_token=$(jwt encode --alg RS256 --secret @gha_privatekey.pem --iss "${github_app_id}" --exp "+${github_app_token_duration_mins}min")
+  rm -f gha_privatekey.pem
+  gha_installation_id=$(curl -s -X GET -H "Authorization: Bearer ${gha_jwt_token}" -H "Accept: application/vnd.github+json" https://api.github.com/app/installations |
+    jq -r --arg target "${github_app_account}" 'map(select(.account.login==$target)) | .[0].id // ""')
+  if [ -z "${gha_installation_id}" ]; then
+    echo "failed to get your Github App installation id. Check your Github App configuration of this resource or on GitHub." >&2
+    exit 1
+  fi
+  github_app_token=$(curl -s -X POST -H "Authorization: Bearer ${gha_jwt_token}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/app/installations/${gha_installation_id}/access_tokens" | jq -r '.token')
+  if [ -z "${github_app_token}" ]; then
+    echo "failed to get Github App token" >&2
+    exit 1
+  fi
+  if ! [[ $uri =~ ^https://github\.com ]]; then
+    echo "Github repository address must begin https:// when using Github App authentication" >&2
+    exit 1
+  fi
+  configure_credentials "$(jq -nr --arg token "${github_app_token}" '{ "source": { "username": "x-username-access", "password": $token } }')"
+else
+  configure_credentials "$payload"
+fi
 
 # If params not defined, get it from source
-if [ -z "$fetch_tags" ] || [ "$fetch_tags" == "null" ]  ; then
-  fetch_tags=$(jq -r '.source.fetch_tags' <<< "$payload")
+if [ -z "$fetch_tags" ] || [ "$fetch_tags" == "null" ]; then
+  fetch_tags=$(jq -r '.source.fetch_tags' <<<"$payload")
 fi
 
 configure_git_global "${git_config_payload}"
@@ -78,14 +106,14 @@ if [ -n "$override_branch" ]; then
 fi
 
 depthflag=""
-if test "$depth" -gt 0 2> /dev/null; then
+if test "$depth" -gt 0 2>/dev/null; then
   depthflag="--depth $depth"
 fi
 
 tagflag=""
-if [ "$fetch_tags" == "false" ] ; then
+if [ "$fetch_tags" == "false" ]; then
   tagflag="--no-tags"
-elif [ -n "$tag_filter" ] || [ -n "$tag_regex" ] || [ "$fetch_tags" == "true" ] ; then
+elif [ -n "$tag_filter" ] || [ -n "$tag_regex" ] || [ "$fetch_tags" == "true" ]; then
   tagflag="--tags"
 fi
 
@@ -103,7 +131,7 @@ git fetch origin refs/notes/*:refs/notes/* $tagflag
 if [ "$depth" -gt 0 ]; then
   "$bin_dir"/deepen_shallow_clone_until_ref_is_found_then_check_out "$depth" "$ref" "$tagflag"
 else
-  if [ "$search_remote_refs_flag" == "true" ] && ! [ -z "$branchflag" ] && ! git rev-list -1 $ref 2> /dev/null > /dev/null; then
+  if [ "$search_remote_refs_flag" == "true" ] && ! [ -z "$branchflag" ] && ! git rev-list -1 $ref 2>/dev/null >/dev/null; then
     change_ref=$(git ls-remote origin | grep $ref | cut -f2)
     if ! [ -z "$change_ref" ]; then
       echo "$ref not found locally, but search_remote_refs is enabled. Attempting to fetch $change_ref first."
@@ -126,12 +154,12 @@ commit_not_signed() {
   exit 1
 }
 
-if [ ! -z "${commit_verification_keys}" ] || [ ! -z "${commit_verification_key_ids}" ] ; then
+if [ ! -z "${commit_verification_keys}" ] || [ ! -z "${commit_verification_key_ids}" ]; then
   if [ ! -z "${commit_verification_keys}" ]; then
     echo "${commit_verification_keys}" | gpg --batch --import || invalid_key "${commit_verification_keys}"
   fi
   if [ ! -z "${commit_verification_key_ids}" ]; then
-    echo "${commit_verification_key_ids}" | \
+    echo "${commit_verification_key_ids}" |
       xargs --no-run-if-empty -n1 gpg --batch --keyserver $gpg_keyserver --recv-keys
   fi
   git verify-commit $(git rev-list -n 1 $ref) || commit_not_signed
@@ -145,7 +173,6 @@ if [ -f $GIT_CRYPT_KEY_PATH ]; then
   echo "unlocking git repo"
   git-crypt unlock $GIT_CRYPT_KEY_PATH
 fi
-
 
 submodule_parameters=""
 if [ "$submodule_remote" != "false" ]; then
@@ -178,7 +205,7 @@ if [ "$submodules" != "none" ]; then
     fi
 
     # check for ssh submodule_credentials
-    submodule_cred=$(jq --arg submodule_url "${submodule_url}" '.source.submodule_credentials // [] | [.[] | select(.url==$submodule_url)] | first // empty' <<< ${payload})
+    submodule_cred=$(jq --arg submodule_url "${submodule_url}" '.source.submodule_credentials // [] | [.[] | select(.url==$submodule_url)] | first // empty' <<<${payload})
 
     if [[ -z ${submodule_cred} ]]; then
 
@@ -190,15 +217,15 @@ if [ "$submodules" != "none" ]; then
       # create or re-initialize ssh-agent
       init_ssh_agent
 
-      private_key=$(jq -r '.private_key' <<< ${submodule_cred})
-      passphrase=$(jq -r '.private_key_passphrase // empty' <<< ${submodule_cred})
+      private_key=$(jq -r '.private_key' <<<${submodule_cred})
+      passphrase=$(jq -r '.private_key_passphrase // empty' <<<${submodule_cred})
 
       private_key_path=$(mktemp -t git-resource-submodule-private-key.XXXXXX)
-      echo "${private_key}" > ${private_key_path}
+      echo "${private_key}" >${private_key_path}
       chmod 0600 ${private_key_path}
 
       # add submodule private_key identity
-      SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=$(dirname $0)/askpass.sh GIT_SSH_PRIVATE_KEY_PASS="$passphrase" DISPLAY= ssh-add $private_key_path > /dev/null
+      SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=$(dirname $0)/askpass.sh GIT_SSH_PRIVATE_KEY_PASS="$passphrase" DISPLAY= ssh-add $private_key_path >/dev/null
 
       git submodule update --init --no-fetch $depthflag $submodule_parameters "$submodule_path"
 
@@ -226,33 +253,33 @@ fi
 
 # Store committer email in .git/committer. Can be used to send email to last committer on failed build
 # Using https://github.com/mdomke/concourse-email-resource for example
-git --no-pager log -1 --pretty=format:"%ae" > .git/committer
+git --no-pager log -1 --pretty=format:"%ae" >.git/committer
 
-git --no-pager log -1 --pretty=format:"%an" > .git/committer_name
+git --no-pager log -1 --pretty=format:"%an" >.git/committer_name
 
 # Store git-resource returned version ref .git/ref. Useful to know concourse
 # pulled ref in following tasks and resources.
-echo "${return_ref}" > .git/ref
+echo "${return_ref}" >.git/ref
 
 # Store original cloned branch in .git/branch
-git name-rev --name-only HEAD > .git/branch
+git name-rev --name-only HEAD >.git/branch
 
 # Store short ref with templating. Useful to build Docker images with
 # a custom tag
-echo "${return_ref}" | cut -c1-7 | awk "{ printf \"${short_ref_format}\", \$1 }" > .git/short_ref
+echo "${return_ref}" | cut -c1-7 | awk "{ printf \"${short_ref_format}\", \$1 }" >.git/short_ref
 
 # Store commit message in .git/commit_message. Can be used to inform about
 # the content of a successfull build.
 # Using https://github.com/cloudfoundry-community/slack-notification-resource
 # for example
-git log -1 --format=format:%B > .git/commit_message
+git log -1 --format=format:%B >.git/commit_message
 
 # Store commit date in .git/commit_timestamp. Can be used for tagging builds
-git log -1 --format=%cd --date=${timestamp_format} > .git/commit_timestamp
+git log -1 --format=%cd --date=${timestamp_format} >.git/commit_timestamp
 
 # Store describe_ref when available. Useful to build Docker images with
 # a custom tag, or package to publish
-echo "$(git describe ${describe_ref_options})" > .git/describe_ref
+echo "$(git describe ${describe_ref_options})" >.git/describe_ref
 
 metadata=$(git_metadata)
 
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -23,24 +23,52 @@ payload="$(cat <&0)"
 load_pubkey "$payload"
 configure_https_tunnel "$payload"
 configure_git_ssl_verification "$payload"
-configure_credentials "$payload"
 
-uri=$(jq -r '.source.uri // ""' <<< "$payload")
-branch=$(jq -r '.source.branch // ""' <<< "$payload")
-git_config_payload=$(jq -r '.source.git_config // []' <<< "$payload")
-repository=$(jq -r '.params.repository // ""' <<< "$payload")
-tag=$(jq -r '.params.tag // ""' <<< "$payload")
-tag_prefix=$(jq -r '.params.tag_prefix // ""' <<< "$payload")
-rebase=$(jq -r '.params.rebase // false' <<< "$payload")
-merge=$(jq -r '.params.merge // false' <<< "$payload")
-returning=$(jq -r '.params.returning // "merged"' <<< "$payload")
-force=$(jq -r '.params.force // false' <<< "$payload")
-only_tag=$(jq -r '.params.only_tag // false' <<< "$payload")
-annotation_file=$(jq -r '.params.annotate // ""' <<< "$payload")
-notes_file=$(jq -r '.params.notes // ""' <<< "$payload")
-override_branch=$(jq -r '.params.branch // ""' <<< "$payload")
+uri=$(jq -r '.source.uri // ""' <<<"$payload")
+branch=$(jq -r '.source.branch // ""' <<<"$payload")
+git_config_payload=$(jq -r '.source.git_config // []' <<<"$payload")
+repository=$(jq -r '.params.repository // ""' <<<"$payload")
+tag=$(jq -r '.params.tag // ""' <<<"$payload")
+tag_prefix=$(jq -r '.params.tag_prefix // ""' <<<"$payload")
+rebase=$(jq -r '.params.rebase // false' <<<"$payload")
+merge=$(jq -r '.params.merge // false' <<<"$payload")
+returning=$(jq -r '.params.returning // "merged"' <<<"$payload")
+force=$(jq -r '.params.force // false' <<<"$payload")
+only_tag=$(jq -r '.params.only_tag // false' <<<"$payload")
+annotation_file=$(jq -r '.params.annotate // ""' <<<"$payload")
+notes_file=$(jq -r '.params.notes // ""' <<<"$payload")
+override_branch=$(jq -r '.params.branch // ""' <<<"$payload")
 # useful for pushing to special ref types like refs/for in gerrit.
-refs_prefix=$(jq -r '.params.refs_prefix // "refs/heads"' <<< "$payload")
+refs_prefix=$(jq -r '.params.refs_prefix // "refs/heads"' <<<"$payload")
+github_app_account=$(jq -r '.source.github_app_account // ""' <<<"$payload")
+github_app_id=$(jq -r '.source.github_app_id // ""' <<<"$payload")
+github_app_private_key=$(jq -r '.source.github_app_private_key // ""' <<<"$payload")
+github_app_token_duration_mins=$(jq -r '.source.github_app_token_duration // "3"' <<<"$payload")
+
+# Github App configuration
+if [ -n "${github_app_account}" ] && [ -n "${github_app_id}" ] && [ -n "${github_app_private_key}" ]; then
+  echo "${github_app_private_key}" >gha_privatekey.pem
+  gha_jwt_token=$(jwt encode --alg RS256 --secret @gha_privatekey.pem --iss "${github_app_id}" --exp "+${github_app_token_duration_mins}min")
+  rm -f gha_privatekey.pem
+  gha_installation_id=$(curl -s -X GET -H "Authorization: Bearer ${gha_jwt_token}" -H "Accept: application/vnd.github+json" https://api.github.com/app/installations |
+    jq -r --arg target "${github_app_account}" 'map(select(.account.login==$target)) | .[0].id // ""')
+  if [ -z "${gha_installation_id}" ]; then
+    echo "failed to get your Github App installation id. Check your Github App configuration of this resource or on GitHub." >&2
+    exit 1
+  fi
+  github_app_token=$(curl -s -X POST -H "Authorization: Bearer ${gha_jwt_token}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/app/installations/${gha_installation_id}/access_tokens" | jq -r '.token')
+  if [ -z "${github_app_token}" ]; then
+    echo "failed to get Github App token" >&2
+    exit 1
+  fi
+  if ! [[ $uri =~ ^https://github\.com ]]; then
+    echo "Github repository address must begin https:// when using Github App authentication" >&2
+    exit 1
+  fi
+  configure_credentials "$(jq -nr --arg token "${github_app_token}" '{ "source": { "username": "x-username-access", "password": $token } }')"
+else
+  configure_credentials "$payload"
+fi
 
 configure_git_global "${git_config_payload}"
 
@@ -123,11 +151,11 @@ push_with_result_check() {
   # oh god this is really the only way to do this
   result_file=$(mktemp $TMPDIR/git-result.XXXXXX)
 
-  echo 0 > $result_file
+  echo 0 >$result_file
 
   {
     tag 2>&1 && push_src_and_tags 2>&1 && add_and_push_notes 2>&1 || {
-      echo $? > $result_file
+      echo $? >$result_file
     }
   } | tee $TMPDIR/push-failure
 
